### PR TITLE
branch filter support

### PR DESCRIPTION
**Pull request by czsilence**
## description

add a branch filter to jenkins job, only push event with matched ref name should trigger job.

## Types of changes

- [ x] New feature (non-breaking change which adds functionality)

## Further comments

- add `"branch filter"` field in job config, default value set to `"master"`
- if set `"branch filter"` to empty or `"*"`, means to handle any ref in this job
- otherwise, only trigger job while ref name ends with value of `"branch filter"`

### CODE REVIEW

**Comment by sanderv32** [comment]
Is this still work in progress or can this be merged?

**Comment by czsilence** [comment]
i have test in local server and works fine. i will write a test for it later today.

**Comment by czsilence** [comment]
> Is this still work in progress or can this be merged? Also can you write a test for this new feature?

i have added test case to branch filter. and i changed default filter to empty so i will compatible prev version.

**Comment by sanderv32** [comment]
The checks are green, so if you're ready i can merge

**Comment by czsilence** [comment]
> The checks are green, so if you're ready i can merge

that will be great. i think this feature is very useful.

**Comment by urusha** [comment]
@sanderv32 Could it be released, please, or where could I find master build?

**Pull request merged**
