### PR TITLE
Get secret from new GoGS header.

### PR DESCRIPTION
**Pull request by SMEmp**
Falls back to pulling from JSON body if no header is sent.

My Java is probably a bit rusty, but I figured this was a good starting place for the discussion.

Regarding issue #14.

### CODE REVIEW

**Comment by tkisme** [comment]
Secret will be sent as SHA256 HMAC hex digest of payload via X-Gogs-Signature header
Did it need decryption?

**Comment by sanderv32** [comment]
Look at code of Gogs line [497](https://github.com/gogits/gogs/blob/6ec859f2b0c1bade67d04f740ec4b9ac9ae0ec98/models/webhook.go#L497). It's not enough to just get the new header with value and pass this to the plugin. This will break authentication. Doing a pull request means you also test the feature you build in.

**Comment by SMEmp** [comment]
> Doing a pull request means you also test the feature you build in.

No, a pull request is an issue with code attached.  The goal is to get a discussion started.

**Comment by sanderv32** [comment]
Then instead of doing a PR create an issue and discuss it. Doing a PR means you add working code which you tested and participate in the project by creating a solution for an issue or even a new feature.

**Comment by SMEmp** [comment]
Apologies, difference in culture.  Will refrain from doing so here in future.

**Comment by sanderv32** [comment]
No problem :-)

**Pull request closed without merging**
