### PR TITLE
Support pipeline jobs

### PR DESCRIPTION
**Pull request by ssouris**
Hi there,

it's really great that your plugin became official.
With this commit I am enabling the execution of pipeline jobs.

Please take a look and if you agree maybe add to your next release :)

Thanks and congrats on your plugin publishing.

### CODE REVIEW

**Comment by sanderv32** [comment]
I will look at the changes tomorrow, and if everything is alright i will merge them into version 1.0.5.

**Comment by xperimental** [comment]
I also noticed yesterday that this plugin does not recognize "Pipeline" jobs. My fix just changes the use of `AbstractProject` to `BuildableItem` which is an interface also implemented by the `WorkflowJob`. This seems like a much simpler solution, but I do not know if this has any unintended consequences.

You can see my version in the ["fix-job" branch of my fork](https://github.com/jenkinsci/gogs-webhook-plugin/compare/master...xperimental:fix-job). I didn't want to open another PR, but can do that if you think that approach is better.

**Comment by sanderv32** [comment]
I will check your pull request and also the previous pull request if this is will not break standard functionality.

**Comment by ehirsch** [comment]
+1 for this one. I just spend some hours finding out that pipeline jobs are not supported yet. Anything I can do to get this merged?

**Comment by ssouris** [comment]
@ehirsch sorry to intervene here but if you are really in a hurry, you can always compile it yourself and import it into Jenkins.

**Comment by sanderv32** [comment]
I want to make sure that also the current functionality doesn't break. It should not be that after the pull only pipeline builds will work and other users will suffer.

**Comment by ssouris** [comment]
@sanderv32 I tried on my machine with freestyle jobs and pipeline jobs and it worked :)
So no pressure at all take your time and create a stable build. 
I am just giving @ehirsch an alternative until then. :)

**Comment by ehirsch** [comment]
@ssouris I am not that good in jenkins-fu. So your alternative is not an option. But that's no big deal. Now that I know about the limitation I can work around it…
@sanderv32 take your time and thanks for your plugin.

**Comment by bozaro** [comment]
IMHO, fix by @xperimental looks like much better: https://github.com/jenkinsci/gogs-webhook-plugin/compare/master...xperimental:fix-job

**Comment by ssouris** [comment]
@bozaro and @all I agree with you it is very very simple. 
Nonetheless, @xperimental has not tested his solution. 
IMHO we should not push untested code and also it not the maintainers job to try an untested PR.
:)

**Comment by bozaro** [comment]
I try fix https://github.com/jenkinsci/gogs-webhook-plugin/compare/master...xperimental:fix-job on my Jenkins instance and it looks like work.

**Comment by xperimental** [comment]
> Nonetheless, @xperimental has not tested his solution.

Sorry for the misunderstanding, but my implementation is _not_ untested. I have been running a build using my version since before posting the comment on this PR. The part with the "unintended consequences" should just highlight that I have not tested it for anything apart from what I use personally (which are "Free Style" and pipeline jobs).

**Comment by sanderv32** [comment]
@ssouris I must admit that the pull request of @xperimental is at the moment the cleanest solution. Are you doing extra stuff which is needed?

**Comment by ssouris** [comment]
No @sanderv32 no extra stuff just borrowed code from gitlab plugin.

**Comment by sanderv32** [comment]
Decided to merge request #2 because impact is minimal to the plugin.

**Pull request closed without merging**
